version: '3.8'

services:
  mysql:
    image: mysql:8.0-debian
    container_name: chattingo-mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattingo-network

  backend:
  image: chattingo_backend:latest
  build:
    context: ./backend
  restart: always           # <- string value, correctly indented
  depends_on:
    - mysql
  env_file:
    - ./backend/.env
  volumes:
    - ./backend:/usr/local/app
  ports:
    - "8080:8080"
  networks:
    - chattingo-network

  frontend:
  build:
    context: ./frontend
  restart: always
  depends_on:
    - backend
  ports:
    - "80:80"
  networks:
    - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:
