version: '3.8'

services:
  mysql:
    image: mysql:8.0-debian
    container_name: chattingo-mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattingo-network

  backend:
    image: laxmi007/chattingo-backend:latest
    container_name: chattingo-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - chattingo-network

  frontend:
    image: chattingo-frontend
    container_name: chattingo-frontend
    ports:
      - "80:80"
    networks:
      - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:

