version: '3.8'

services:
  mysql:
    image: mysql:8.0-debian
    container_name: chattingo-mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattingo-network

  backend:
  build:
    context: ./backend            # VPS backend code folder path
  restart: always
  depends_on:
    - mysql
  env_file:
    - ./backend/.env              # strong JWT secret, DB credentials
  volumes:
    - ./backend:/usr/local/app    # code changes reflect live
  ports:
    - "8080:8080"
  networks:
    - chattingo-network

  frontend:
  build:
    context: ./frontend
  restart: always
  depends_on:
    - backend
  ports:
    - "80:80"
  networks:
    - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:
