services:
  db:
    container_name: chattingo-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chattingo-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chattingo-backend
    depends_on:
      db:
        condition: service_started
    restart: always
    environment:
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    networks:
      - chattingo-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      environment:
        REACT_APP_API_URL: http://72.60.111.24:8080
    container_name: chattingo-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    networks:
      - chattingo-net

volumes:
  db_data:

networks:
  chattingo-net:
    driver: bridge
