version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: chattingo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chattingo-network

  backend:
    image: chattingo_backend:latest   # backend image name
    build:
      context: ./backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/local/app
    ports:
      - "8080:8080"
    networks:
      - chattingo-network

  frontend:
    image: chattingo_frontend:latest  # frontend image name
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:
    driver: bridge
