version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: chattingo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chattingo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chattingo-net

  backend:
    build:
      context: ./backend
    container_name: chattingo-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - chattingo-net

  frontend:
    build:
      context: ./frontend
    container_name: chattingo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - chattingo-net

volumes:
  db_data:

networks:
  chattingo-net:
    driver: bridge
